<?php

declare(strict_types=1);

/**
 * Language metadata for Kidney Tales
 * 
 * @author Ľubomír Polaščín
 * @package KidneyTales
 * @version 2025.08.1.1
 * 
 * This file contains an associative array mapping language codes to their
 * English names, Native names, and Country Codes.
 * 
 */
// @file /resources/languages.php

// code => [English name, Native name, Country code]
return [

  // --- EUROPEAN LANGUAGES ---
  'eo' => ['Esperanto', 'Esperanto', 'eo'],
  'sk' => ['Slovak', 'Slovenčina', 'sk'],
  'en' => ['English', 'English', 'gb'],
  'cs' => ['Czech', 'Čeština', 'cz'],
  'de' => ['German', 'Deutsch', 'de'],
  'pl' => ['Polish', 'Polski', 'pl'],
  'en-us' => ['English (US)', 'English (US)', 'us'],
  'en-gb' => ['English (UK)', 'English (UK)', 'gb'],
  'en-ie' => ['English (Ireland)', 'English (Ireland)', 'ie'],
  'hu' => ['Hungarian', 'Magyar', 'hu'],
  'ru' => ['Russian', 'Русский', 'ru'],
  'uk' => ['Ukrainian', 'Українська', 'ua'],
  'nl' => ['Dutch', 'Nederlands', 'nl'],
  'it' => ['Italian', 'Italiano', 'it'],
  'fr' => ['French', 'Français', 'fr'],
  'es' => ['Spanish', 'Español', 'es'],
  'pt' => ['Portuguese', 'Português', 'pt'],
  'bg' => ['Bulgarian', 'Български', 'bg'],
  'ro' => ['Romanian', 'Română', 'ro'],
  'sl' => ['Slovenian', 'Slovenščina', 'si'],
  'hr' => ['Croatian', 'Hrvatski', 'hr'],
  'lt' => ['Lithuanian', 'Lietuvių', 'lt'],
  'lv' => ['Latvian', 'Latviešu', 'lv'],
  'et' => ['Estonian', 'Eesti', 'ee'],
  'da' => ['Danish', 'Dansk', 'dk'],
  'no' => ['Norwegian', 'Norsk', 'no'],
  'sv' => ['Swedish', 'Svenska', 'se'],
  'fi' => ['Finnish', 'Suomi', 'fi'],
  'is' => ['Icelandic', 'Íslenska', 'is'],
  'el' => ['Greek', 'Ελληνικά', 'gr'],
  'la' => ['Latin', 'Latina', 'va'],
  'mt' => ['Maltese', 'Malti', 'mt'],
  'rom' => ['Romani', 'Romani', 'ro'],
  'rue' => ['Rusyn (Ruthenian)', 'Rusyn', 'rue'],
  'tr' => ['Turkish', 'Türkçe', 'tr'],
  // Other languages alphabetically sorted
  'az' => ['Azerbaijani', 'Azərbaycanca', 'az'],
  'ba' => ['Bashkir', 'Башҡорт', 'ru'],
  'be' => ['Belarusian', 'Беларуская', 'by'],
  'bs' => ['Bosnian', 'Bosanski', 'ba'],
  'ca' => ['Catalan', 'Català', 'es'],
  'cy' => ['Welsh', 'Cymraeg', 'gb'],
  'de-at' => ['German (Austria)', 'Deutsch (Österreich)', 'at'],
  'de-be' => ['German (Belgium)', 'Deutsch (Belgien)', 'be'],
  'de-ch' => ['German (Switzerland)', 'Deutsch (Schweiz)', 'ch'],
  'de-li' => ['German (Liechtenstein)', 'Deutsch (Liechtenstein)', 'li'],
  'de-lu' => ['German (Luxembourg)', 'Deutsch (Luxemburg)', 'lu'],
  'en-gb' => ['English (UK)', 'English (UK)', 'gb'],
  'en-ie' => ['English (Ireland)', 'English (Ireland)', 'ie'],
  'eu' => ['Basque', 'Euskara', 'es'],
  'fo' => ['Faroese', 'Føroyskt', 'fo'],
  'fr-be' => ['French (Belgium)', 'Français (Belgique)', 'be'],
  'fr-ch' => ['French (Switzerland)', 'Français (Suisse)', 'ch'],
  'fr-ht' => ['French (Haiti)', 'Français (Haïti)', 'ht'],
  'fr-lu' => ['French (Luxembourg)', 'Français (Luxembourg)', 'lu'],
  'fr-mc' => ['French (Monaco)', 'Français (Monaco)', 'mc'],
  'ga' => ['Irish', 'Gaeilge', 'ie'],
  'gd' => ['Scottish Gaelic', 'Gàidhlig', 'gb'],
  'gl' => ['Galician', 'Galego', 'es'],
  'it-ch' => ['Italian (Switzerland)', 'Italiano (Svizzera)', 'ch'],
  'it-sm' => ['Italian (San Marino)', 'Italiano (San Marino)', 'sm'],
  'it-va' => ['Italian (Vatican City)', 'Italiano (Città del Vaticano)', 'va'],
  'kl' => ['Kalaallisut', 'Kalaallisut', 'gl'],
  'lad' => ['Ladino', 'Ladino', 'es'],
  'lb' => ['Luxembourgish', 'Lëtzebuergesch', 'lu'],
  'mk' => ['Macedonian', 'Македонски', 'mk'],
  'mo' => ['Moldovan', 'Moldovenească', 'md'],
  'mrj' => ['Hill Mari', 'Кырык мары', 'ru'],
  'nl-be' => ['Dutch (Belgium)', 'Vlaams', 'be'],
  'pt-ao' => ['Portuguese (Angola)', 'Português (Angola)', 'ao'],
  'pt-cv' => ['Portuguese (Cape Verde)', 'Português (Cabo Verde)', 'cv'],
  'pt-gw' => ['Portuguese (Guinea-Bissau)', 'Português (Guiné-Bissau)', 'gw'],
  'pt-lu' => ['Portuguese (Luxembourg)', 'Português (Luxemburgo)', 'lu'],
  'pt-mo' => ['Portuguese (Macau)', 'Português (Macau)', 'mo'],
  'pt-mz' => ['Portuguese (Mozambique)', 'Português (Moçambique)', 'mz'],
  'pt-pt' => ['Portuguese (Portugal)', 'Português (Portugal)', 'pt'],
  'pt-st' => ['Portuguese (São Tomé and Príncipe)', 'Português (São Tomé e Príncipe)', 'st'],
  'pt-tl' => ['Portuguese (Timor-Leste)', 'Português (Timor-Leste)', 'tl'],
  'rm' => ['Romansh', 'Rumantsch', 'ch'],
  'ro-md' => ['Romanian (Moldova)', 'Română (Moldova)', 'md'],
  'ru-by' => ['Russian (Belarus)', 'Русский (Беларусь)', 'by'],
  'ru-kz' => ['Russian (Kazakhstan)', 'Русский (Казахстан)', 'kz'],
  'ru-ua' => ['Russian (Ukraine)', 'Русский (Украина)', 'ua'],
  'se' => ['Northern Sami', 'Sámegiella', 'no'],
  'smj' => ['Lule Sami', 'Julevsámegiella', 'se'],
  'sma' => ['Southern Sami', 'Åarjelsaemien gïele', 'se'],
  'smn' => ['Inari Sami', 'anarâškielâ', 'fi'],
  'sms' => ['Skolt Sami', 'Sääʹmǩiõll', 'fi'],
  'sq' => ['Albanian', 'Shqip', 'al'],
  'aln' => ['Gheg Albanian', 'Gegë', 'al'],
  'sr' => ['Serbian', 'Српски', 'rs'],
  'sr-latn' => ['Serbian (Latin)', 'Srpski (Latinica)', 'rs'],
  'ukr' => ['Ukrainian (alt)', 'Українська', 'ua'],

  // --- MINORITY & REGIONAL EUROPEAN LANGUAGES ---
  'an' => ['Aragonese', 'Aragonés', 'es'],
  'ast' => ['Asturian', 'Asturianu', 'es'],
  'br' => ['Breton', 'Brezhoneg', 'fr'],
  'dsb' => ['Lower Sorbian', 'Dolnoserbšćina', 'de'],
  'fy' => ['Frisian', 'Frysk', 'nl'],
  'fur' => ['Friulian', 'Furlan', 'it'],
  'gv' => ['Manx', 'Gaelg', 'im'],
  'hsb' => ['Upper Sorbian', 'Hornjoserbšćina', 'de'],
  'kw' => ['Cornish', 'Kernewek', 'gb'],
  'nds' => ['Low German', 'Plattdüütsch', 'de'],
  'nds-nl' => ['Low Saxon (Netherlands)', 'Nedersaksisch', 'nl'],
  'oc' => ['Occitan', 'Occitan', 'fr'],
  'sc' => ['Sardinian', 'Sardu', 'it'],
  'sco' => ['Scots', 'Scots', 'gb'],
  'sli' => ['Silesian (Germany)', 'Schläsisch', 'de'],
  'szl' => ['Silesian', 'Ślůnski', 'pl'],
  'vec' => ['Venetian', 'Vèneto', 'it'],
  'vls' => ['West Flemish', 'West-Vlams', 'be'],
  'wa' => ['Walloon', 'Walon', 'be'],

  // --- ASIAN LANGUAGES ---
  'ar-bh' => ['Arabic (Bahrain)', 'العربية (البحرين)', 'bh'],
  'ar-dz' => ['Arabic (Algeria)', 'العربية (الجزائر)', 'dz'],
  'ar-eg' => ['Arabic (Egypt)', 'العربية (مصر)', 'eg'],
  'ar-iq' => ['Arabic (Iraq)', 'العربية (العراق)', 'iq'],
  'ar-jo' => ['Arabic (Jordan)', 'العربية (الأردن)', 'jo'],
  'ar-kw' => ['Arabic (Kuwait)', 'العربية (الكويت)', 'kw'],
  'ar-lb' => ['Arabic (Lebanon)', 'العربية (لبنان)', 'lb'],
  'ar-ly' => ['Arabic (Libya)', 'العربية (ليبيا)', 'ly'],
  'ar-ma' => ['Arabic (Morocco)', 'العربية (المغرب)', 'ma'],
  'ar-om' => ['Arabic (Oman)', 'العربية (عمان)', 'om'],
  'ar-ps' => ['Arabic (Palestine)', 'العربية (فلسطين)', 'ps'],
  'ar-qa' => ['Arabic (Qatar)', 'العربية (قطر)', 'qa'],
  'ar-sa' => ['Arabic (Saudi Arabia)', 'العربية (السعودية)', 'sa'],
  'ar-sd' => ['Arabic (Sudan)', 'العربية (السودان)', 'sd'],
  'ar-sy' => ['Arabic (Syria)', 'العربية (سوريا)', 'sy'],
  'ar-ae' => ['Arabic (UAE)', 'العربية (الإمارات)', 'ae'],
  'ar-ye' => ['Arabic (Yemen)', 'العربية (اليمن)', 'ye'],
  'zh-hk' => ['Chinese (Hong Kong)', '中文 (香港)', 'hk'],
  'zh-mo' => ['Chinese (Macau)', '中文 (澳門)', 'mo'],
  'zh-sg' => ['Chinese (Singapore)', '中文 (新加坡)', 'sg'],
  'ar' => ['Arabic', 'العربية', 'sa'],
  'awa' => ['Awadhi', 'अवधी', 'in'],
  'bho' => ['Bhojpuri', 'भोजपुरी', 'in'],
  'bn' => ['Bengali', 'বাংলা', 'bd'],
  'bo' => ['Tibetan', 'བོད་སྐད་', 'cn'],
  'brx' => ['Bodo', 'बर', 'in'],
  'ckb' => ['Central Kurdish', 'کوردیی ناوەندی', 'iq'],
  'doi' => ['Dogri', 'डोगरी', 'in'],
  'en-hk' => ['English (Hong Kong)', 'English (Hong Kong)', 'hk'],
  'en-in' => ['English (India)', 'English (India)', 'in'],
  'en-my' => ['English (Malaysia)', 'English (Malaysia)', 'my'],
  'en-ph' => ['English (Philippines)', 'English (Philippines)', 'ph'],
  'en-pk' => ['English (Pakistan)', 'English (Pakistan)', 'pk'],
  'en-sg' => ['English (Singapore)', 'English (Singapore)', 'sg'],
  'fa' => ['Persian', 'فارسی', 'ir'],
  'gom' => ['Goan Konkani', 'कोंकणी', 'in'],
  'gu' => ['Gujarati', 'ગુજરાતી', 'in'],
  'hi' => ['Hindi', 'हिन्दी', 'in'],
  'id' => ['Indonesian', 'Bahasa Indonesia', 'id'],
  'ja' => ['Japanese', '日本語', 'jp'],
  'kk' => ['Kazakh', 'Қазақ', 'kz'],
  'km' => ['Khmer', 'ភាសាខ្មែរ', 'kh'],
  'kn' => ['Kannada', 'ಕನ್ನಡ', 'in'],
  'ks' => ['Kashmiri', 'कॉशुर', 'in'],
  'ky' => ['Kyrgyz', 'Кыргызча', 'kg'],
  'lo' => ['Lao', 'ລາວ', 'la'],
  'mag' => ['Magahi', 'मगही', 'in'],
  'mai' => ['Maithili', 'मैथिली', 'in'],
  'ml' => ['Malayalam', 'മലയാളം', 'in'],
  'mn' => ['Mongolian', 'Монгол', 'mn'],
  'mni' => ['Manipuri', 'মৈতৈলোন্', 'in'],
  'mr' => ['Marathi', 'मराठी', 'in'],
  'ms' => ['Malay', 'Bahasa Melayu', 'my'],
  'my' => ['Burmese', 'မြန်မာ', 'mm'],
  'ne' => ['Nepali', 'नेपाली', 'np'],
  'pa' => ['Punjabi', 'ਪੰਜਾਬੀ', 'in'],
  'ps' => ['Pashto', 'پښتو', 'af'],
  'sa' => ['Sanskrit', 'संस्कृतम्', 'in'],
  'sat' => ['Santali', 'ᱥᱟᱱᱛᱟᱲᱤ', 'in'],
  'si' => ['Sinhala', 'සිංහල', 'lk'],
  'syl' => ['Sylheti', 'ꠍꠤꠟꠐꠤ', 'bd'],
  'ta' => ['Tamil', 'தமிழ்', 'in'],
  'te' => ['Telugu', 'తెలుగు', 'in'],
  'th' => ['Thai', 'ไทย', 'th'],
  'tk' => ['Turkmen', 'Türkmen', 'tm'],
  'ug' => ['Uyghur', 'ئۇيغۇرچە', 'cn'],
  'ur' => ['Urdu', 'اُردُو', 'pk'],
  'uz' => ['Uzbek', 'Oʻzbek', 'uz'],
  'vi' => ['Vietnamese', 'Tiếng Việt', 'vn'],
  'yi' => ['Yiddish', 'ייִדיש', 'il'],
  'zh' => ['Chinese', '中文', 'cn'],
  'zh-cn' => ['Chinese (Simplified)', '简体中文', 'cn'],
  'zh-tw' => ['Chinese (Traditional)', '繁體中文', 'tw'],

  // --- AFRICAN LANGUAGES ---
  'am' => ['Amharic', 'አማርኛ', 'et'],
  'ar-tn' => ['Arabic (Tunisia)', 'العربية (تونس)', 'tn'],
  'en-gh' => ['English (Ghana)', 'English (Ghana)', 'gh'],
  'en-za' => ['English (South Africa)', 'English (South Africa)', 'za'],
  'ha' => ['Hausa', 'Hausa', 'ng'],
  'ig' => ['Igbo', 'Asụsụ Igbo', 'ng'],
  'kg' => ['Kongo', 'Kikongo', 'cd'],
  'ln' => ['Lingala', 'Lingála', 'cd'],
  'lua' => ['Luba-Lulua', 'Tshiluba', 'cd'],
  'mg' => ['Malagasy', 'Malagasy', 'mg'],
  'rw' => ['Kinyarwanda', 'Ikinyarwanda', 'rw'],
  'sn' => ['Shona', 'chiShona', 'zw'],
  'so' => ['Somali', 'Soomaaliga', 'so'],
  'ss' => ['Swati', 'SiSwati', 'sz'],
  'st' => ['Southern Sotho', 'Sesotho', 'za'],
  'sw' => ['Swahili', 'Kiswahili', 'ke'],
  'tn' => ['Tswana', 'Setswana', 'za'],
  'ts' => ['Tsonga', 'Xitsonga', 'za'],
  'tzm' => ['Berber (Tamazight)', 'ⵜⴰⵎⴰⵣⵉⵖⵜ', 'ma'],
  've' => ['Venda', 'Tshivenda', 'za'],
  'xh' => ['Xhosa', 'isiXhosa', 'za'],
  'yo' => ['Yoruba', 'Yorùbá', 'ng'],
  'zu' => ['Zulu', 'isiZulu', 'za'],

  // --- OCEANIAN LANGUAGES ---
  'bi' => ['Bislama', 'Bislama', 'vu'],
  'ch' => ['Chamorro', 'Chamoru', 'gu'],
  'en-au' => ['English (Australia)', 'English (Australia)', 'au'],
  'en-nz' => ['English (New Zealand)', 'English (New Zealand)', 'nz'],
  'fj' => ['Fijian', 'Vosa Vakaviti', 'fj'],
  'mh' => ['Marshallese', 'Kajin M̧ajeļ', 'mh'],
  'mi' => ['Maori', 'Te Reo Māori', 'nz'],
  'na' => ['Nauruan', 'Dorerin Naoero', 'nr'],
  'pau' => ['Palauan', 'a tekoi er a Belau', 'pw'],
  'rap' => ['Rapa Nui', 'Rapa Nui', 'cl'],
  'rar' => ['Rarotongan', 'Māori Kūki ʻĀirani', 'ck'],
  'sm' => ['Samoan', 'Gagana Samoa', 'ws'],
  'tpi' => ['Tok Pisin', 'Tok Pisin', 'pg'],
  'to' => ['Tongan', 'Faka Tonga', 'to'],

  // --- AMERICAN LANGUAGES ---
  'es-cu' => ['Spanish (Cuba)', 'Español (Cuba)', 'cu'],
  'es-ea' => ['Spanish (Ceuta and Melilla)', 'Español (Ceuta y Melilla)', 'ea'],
  'es-gq' => ['Spanish (Equatorial Guinea)', 'Español (Guinea Ecuatorial)', 'gq'],
  'es-ic' => ['Spanish (Canary Islands)', 'Español (Islas Canarias)', 'ic'],
  'fr-ht' => ['French (Haiti)', 'Français (Haïti)', 'ht'],
  'en-il' => ['English (Israel)', 'English (Israel)', 'il'],
  'en-ng' => ['English (Nigeria)', 'English (Nigeria)', 'ng'],
  'ceb' => ['Cebuano', 'Sinugbuanong Binisaya', 'ph'],
  'cr' => ['Cree', 'ᓀᐦᐃᔭᐍᐏᐣ', 'ca'],
  'en-bz' => ['English (Belize)', 'English (Belize)', 'bz'],
  'es-ar' => ['Spanish (Argentina)', 'Español (Argentina)', 'ar'],
  'es-bo' => ['Spanish (Bolivia)', 'Español (Bolivia)', 'bo'],
  'es-cl' => ['Spanish (Chile)', 'Español (Chile)', 'cl'],
  'es-co' => ['Spanish (Colombia)', 'Español (Colombia)', 'co'],
  'es-cr' => ['Spanish (Costa Rica)', 'Español (Costa Rica)', 'cr'],
  'es-do' => ['Spanish (Dominican Republic)', 'Español (República Dominicana)', 'do'],
  'es-ec' => ['Spanish (Ecuador)', 'Español (Ecuador)', 'ec'],
  'es-gt' => ['Spanish (Guatemala)', 'Español (Guatemala)', 'gt'],
  'es-hn' => ['Spanish (Honduras)', 'Español (Honduras)', 'hn'],
  'es-mx' => ['Spanish (Mexico)', 'Español (México)', 'mx'],
  'es-ni' => ['Spanish (Nicaragua)', 'Español (Nicaragua)', 'ni'],
  'es-pa' => ['Spanish (Panama)', 'Español (Panamá)', 'pa'],
  'es-pe' => ['Spanish (Peru)', 'Español (Perú)', 'pe'],
  'es-pr' => ['Spanish (Puerto Rico)', 'Español (Puerto Rico)', 'pr'],
  'es-py' => ['Spanish (Paraguay)', 'Español (Paraguay)', 'py'],
  'es-sv' => ['Spanish (El Salvador)', 'Español (El Salvador)', 'sv'],
  'es-us' => ['Spanish (United States)', 'Español (Estados Unidos)', 'us'],
  'es-uy' => ['Spanish (Uruguay)', 'Español (Uruguay)', 'uy'],
  'es-ve' => ['Spanish (Venezuela)', 'Español (Venezuela)', 've'],
  'fr-ca' => ['French (Canada)', 'Français (Canada)', 'ca'],
  'pt-br' => ['Portuguese (Brazil)', 'Português (Brasil)', 'br'],
  'pt-ao' => ['Portuguese (Angola)', 'Português (Angola)', 'ao'],
  'pt-cv' => ['Portuguese (Cape Verde)', 'Português (Cabo Verde)', 'cv'],
  'pt-gw' => ['Portuguese (Guinea-Bissau)', 'Português (Guiné-Bissau)', 'gw'],
  'pt-mz' => ['Portuguese (Mozambique)', 'Português (Moçambique)', 'mz'],
  'pt-st' => ['Portuguese (São Tomé and Príncipe)', 'Português (São Tomé e Príncipe)', 'st'],
  'en-ca' => ['English (Canada)', 'English (Canada)', 'ca'],
  'en-jm' => ['English (Jamaica)', 'English (Jamaica)', 'jm'],
  'en-tt' => ['English (Trinidad and Tobago)', 'English (Trinidad and Tobago)', 'tt'],
  'hiligaynon' => ['Hiligaynon', 'Ilonggo', 'ph'],
  'ilo' => ['Ilocano', 'Ilokano', 'ph'],
  'iu' => ['Inuktitut', 'ᐃᓄᒃᑎᑐᑦ', 'ca'],
  'jv' => ['Javanese', 'Basa Jawa', 'id'],
  'pam' => ['Pampangan', 'Kapampangan', 'ph'],
  'su' => ['Sundanese', 'Basa Sunda', 'id'],
  'tl' => ['Tagalog', 'Tagalog', 'ph'],
  'war' => ['Waray', 'Winaray', 'ph'],

  // --- OTHER LANGUAGES ---
  'ia' => ['Interlingua', 'Interlingua', 'ia'],
];
